import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header/Header";
import '@mantine/core/styles.css';
import Footer  from "./Footer/page";

import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import Contact from "./Contact/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
      <MantineProvider>
      <Header/>
      {children}
      <Contact/>
      <Footer/>
      </MantineProvider>
      {/* <main></main> */}
        </body>
    </html>
  );
}
